name: Version Tagging and Multi-Arch Workflow

on:
  push:
    branches:
      - main
      - develop
      - releases/**

jobs:
  tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/arm/v7]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

      - name: Tag version
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/releases/**' }}
        run: |
          git tag v${{ steps.gitversion.outputs.semVer }}
          git push origin v${{ steps.gitversion.outputs.semVer }}

      - name: Push new version
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Version v${{ steps.gitversion.outputs.semVer }} pushed"

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            docker.io/cdaprod/${{ github.repository }}:${{ steps.gitversion.outputs.semVer }}

      - name: Push Docker image to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ steps.gitversion.outputs.semVer }}